#
#spring.session.store-type=redis
#spring.redis.host=192.168.187.135
#spring.redis.port=6379

spring:
  redis:
    host: 192.168.187.135
    port: 6379
  session:
    store-type: redis
server:
  port: 8082