server:
  servlet:
    context-path: /api

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ddd?useSSL=false&serverTimezone=UTC
    password: Root.123456
    username: root