

spring:
  kafka:
    bootstrap-servers: 172.29.96.105:9092,172.29.96.105:9093,172.29.96.105:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      client-id: producer
      retries: 3 # ????0????????????????????
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      # ??????????????ListenerConsumer???????
      # RECORD
      # ????poll()???????????ListenerConsumer???????
      # BATCH
      # ????poll()???????????ListenerConsumer????????????????TIME???
      # TIME
      # ????poll()???????????ListenerConsumer?????????record??????COUNT???
      # COUNT
      # TIME |?COUNT???????????
      # COUNT_TIME
      # ????poll()???????????ListenerConsumer?????, ????Acknowledgment.acknowledge()???
      # MANUAL
      # ????Acknowledgment.acknowledge()?????
      # MANUAL_IMMEDIATE
      ack-mode: manual_immediate
server:
  port: 8888