
spring:
  profiles:
    active: '@spring-boot.profiles.active@'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
      data-locations: classpath*:sql/data.sql
      schema-locations: classpath*:sql/schema.sql
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
server:
  port: 8888