hzz:
  use: h2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: Root.123456
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
